initiald_inventory/authentication/routes.py
import email
from flask import Blueprint, render_template, request, redirect, url_for, flash
from initiald_inventory.models import User, db, check_password_hash
from initiald_inventory.forms import UserLoginForm

# Imports for Flask_login
from flask_login import login_user, logout_user, current_user, login_required


auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)
            db.session.add(user)
            db.session.commit()

            flash(f"account created here are the keys: {email}", 'user-created')

            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')



    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('succesfully received car keys: Via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash("Email/password wrong no keys for you", 'auth-failed')
                return redirect(url_for('auth.signing'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signin.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

initiald_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login.utils import login_required

"""
note that in the code below,
some arguments are specified when creating the Blueprint.
the frist arguemtn, "site", is the GBlueprint's name,
which is used by Flask's routing mechanism

the second arugment, __name__, is the Blueprint's import name,
which Flask uses to locate the Blueprints resources

"""

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

initiald_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Initial D API</title>
</head>
<body>
<!-- nav bar here -->
    <nav class="ct-nav">
        <div>
            <img src="../static/images/projectdv2.jpg" alt="">
        </div>
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home')}}">
                    <li>PROJECT:INITIAL D</li>
                </a>
                <a href="{{ url_for('site.profile') }}">
                    <li>Drivers</li>
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}">
                    <li>Log Out</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signup')}}">
                    <li>Sign Up</li>
                </a>
                <a href="{{ url_for('auth.signin')}}">
                    <li>Sing In</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

initiald_inventory/templates/forms.html
<!-- html produced by the flask form  -->

<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder ="Place Email Here")}}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here")}}
        </fieldset>



        <!-- submitbutton -->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>


</form>